package it.polimi.ingsw.view.beans;

public enum CharacterCardEnumeration {
    EXCHANGE_ENTRANCE_DINING_ROOM,
    STUDENT_TO_ENTRANCE,
    STUDENT_TO_DINING_ROOM,
    PROTECT_ISLAND,
    THREE_STUDENT,
    ISLAND_INFLUENCE,
    MOTHER_NATURE_MOVEMENT,
    NO_COLOUR,
    NO_TOWER,
    STUDENT_TO_ISLAND,
    TAKE_PROFESSOR,
    TWO_POINTS
}
